
// This file has been generated by the GUI designer. Do not modify.
namespace AyoController
{
	public partial class MainGUI
	{
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Button button3;

		public virtual void Build ()
		{
			/*global::Stetic.Gui.Initialize (this);
            // Widget AyoController.MainGUI
            Name = "AyoController.MainGUI";
            Title = global::Mono.Unix.Catalog.GetString ("MainGUI");
            WindowPosition = ((global::Gtk.WindowPosition)(4));
            // Container child AyoController.MainGUI.Gtk.Container+ContainerChild
            alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
            alignment1.Name = "alignment1";
            // Container child alignment1.Gtk.Container+ContainerChild
            fixed1 = new global::Gtk.Fixed ();
            fixed1.Name = "fixed1";
            fixed1.HasWindow = false;
            // Container child fixed1.Gtk.Fixed+FixedChild
            button3 = new global::Gtk.Button ();
            button3.CanFocus = true;
            button3.Name = "button3";
            button3.UseUnderline = true;
            button3.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
            fixed1.Add (button3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(fixed1[button3]));
			w1.X = 316;
			w1.Y = 254;
            alignment1.Add (fixed1);
            Add(alignment1);
			if ((Child != null)) {
                Child.ShowAll ();
			}
            DefaultWidth = 416;
            DefaultHeight = 300;
            Show();*/
		}
	}
}
